-- Site editor defaults used by the owner-friendly admin CMS.
-- Existing customised values are preserved.

INSERT INTO site_settings (setting_key, setting_value, setting_type, description) VALUES
('business_name', 'The Quiz Master General', 'text', 'Public business name'),
('tagline', 'North East England''s Premier Quiz & Entertainment Provider', 'text', 'Short business tagline'),
('business_email', 'info@thequizmastergeneral.com', 'text', 'Public contact email'),
('business_phone', '', 'text', 'Public contact phone number'),
('business_address', '', 'text', 'Business address or coverage note'),
('business_city', 'Newcastle, Durham, Sunderland & surrounding areas', 'text', 'Primary service area'),
('business_postcode', '', 'text', 'Business postcode'),
('business_hours', '', 'text', 'Public opening/contact hours'),
('hero_button_1_text', 'Our Services', 'text', 'Homepage primary button label'),
('hero_button_2_text', 'Book Now', 'text', 'Homepage secondary button label'),
('home_services_title', 'What We Offer', 'text', 'Homepage services section title'),
('home_services_subtitle', 'Professional entertainment services that bring energy and excitement to your venue.', 'text', 'Homepage services section intro'),
('home_events_title', 'Upcoming Events', 'text', 'Homepage events section title'),
('home_reviews_title', 'What Venues Say', 'text', 'Homepage reviews section title'),
('home_gallery_title', 'See Us in Action', 'text', 'Homepage gallery section title'),
('home_team_title', 'Meet the Team', 'text', 'Homepage team section title'),
('services_page_title', 'Our Services', 'text', 'Services page heading'),
('services_page_subtitle', 'Professional entertainment for your venue', 'text', 'Services page intro'),
('events_page_title', 'Our Events', 'text', 'Events page heading'),
('events_page_subtitle', 'Quiz nights, race nights, and special events across the North East', 'text', 'Events page intro'),
('venues_page_title', 'Our Partner Venues', 'text', 'Venues page heading'),
('venues_page_subtitle', 'Bringing entertainment to venues across the North East', 'text', 'Venues page intro'),
('gallery_page_title', 'Gallery', 'text', 'Gallery page heading'),
('gallery_page_subtitle', 'Memories from our amazing events', 'text', 'Gallery page intro'),
('team_page_title', 'Meet The Team', 'text', 'Team page heading'),
('team_page_subtitle', 'The professionals who bring the fun to your venue', 'text', 'Team page intro'),
('contact_page_title', 'Get In Touch', 'text', 'Contact page heading'),
('contact_page_subtitle', 'Let''s discuss how we can bring entertainment to your venue.', 'text', 'Contact page intro'),
('section_order', '["social_proof","about","services","events","reviews","gallery","team","social_media","question_of_day"]', 'json', 'Homepage section order'),
('social_proof_bg_color', '#003DA5', 'text', 'Stats strip background colour'),
('services_bg_color', '#DC143C', 'text', 'Services section background colour'),
('events_bg_color', '#003DA5', 'text', 'Events section background colour'),
('reviews_bg_color', '#DC143C', 'text', 'Reviews section background colour'),
('gallery_bg_color', '#003DA5', 'text', 'Gallery section background colour'),
('team_bg_color', '#DC143C', 'text', 'Team section background colour')
ON CONFLICT (setting_key) DO NOTHING;
